<h2>Libraries</h2>

In [26]:
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.impute import SimpleImputer #For the missing data
from sklearn.compose import ColumnTransformer # Scaling
from sklearn.preprocessing import OneHotEncoder # Scaling categorical
from sklearn.preprocessing import LabelEncoder 
from sklearn.model_selection import train_test_split #spliting
from sklearn.preprocessing import StandardScaler #Scaling

<h2>Data Set</h2>

In [27]:
df = pd.read_csv("Data.csv")
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [29]:
df_infos = df.iloc[:,:-1].values
df_results = df.iloc[:,-1].values
print(df_infos)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [30]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(df_infos[:,1:3]) 
df_infos[:,1:3] = imputer.transform(df_infos[:,1:3])

In [31]:
print(df_infos)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<h5>Encoding categorical variables</h5>

In [32]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
df_infos = np.array(ct.fit_transform(df_infos))
print(df_infos)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [33]:
le = LabelEncoder()
df_results = le.fit_transform(df_results)
print(df_results)

[0 1 0 0 1 1 0 1 0 1]


<h4>Spliting in training and test</h4>

In [34]:
df_results_train , df_results_test , df_infos_train , df_infos_test = train_test_split(df_results, df_infos , test_size= 0.2, random_state= 1 )

In [35]:
print(df_results_train)

[0 1 0 0 1 1 0 1]


In [36]:
print(df_results_test)

[0 1]


In [37]:
print(df_infos_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [38]:
print(df_infos_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


<h3>Scalling</h3>
Standard = (x-mean(x)) / standard deviation(x)<br>
Normalisation = (x-min(x)) / max(x)-min(x)<br>

In [39]:
sc = StandardScaler()
df_infos_train[:, 3:] = sc.fit_transform(df_infos_train[:, 3:])
df_infos_test[:, 3:] = sc.fit_transform(df_infos_test[:, 3:])


In [40]:
print(df_infos_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [41]:
print(df_infos_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
